MAIN_MENU_SETTINGS_STAGE = 'main_menu_settings'
MAIN_MENU_STAGE = 'main_menu'

ROUND_PAUSE_STAGE = 'round_pause'
ROUND_STAGE = 'round'
EXIT_STAGE = 'exit'

LOADING_STAGE = 'loading'

MENUS_STAGES_LISTS = [MAIN_MENU_STAGE, MAIN_MENU_SETTINGS_STAGE]