from settings.screen import SCREEN_H, SCREEN_W, HALF_SCREEN_W, HALF_SCREEN_H

X_POS = 0
Y_POS = SCREEN_H * 0.075
X_SIZE = Y_SIZE = SCREEN_H * 0.7

MIN_SCALE = 1
MAX_SCALE = 2
SCALE_SPEED = 0.025

HEX_SIZE = 34
