DEFAULT_CROSSHAIR_SIZE = 33
DEFAULT_CROSSHAIR_LINE_SIZE = 10
DEFAULT_CROSSHAIR_DOT_EXISTS = False
DEFAULT_CROSSHAIR_DOT_SIZE = 2
DEFAULT_CROSSHAIR_LINE_CENTER_DISTANCE = 4
DEFAULT_CROSSHAIR_LINE_WIGHT = 2
DEFAULT_CROSSHAIR_ROTATE = 45
DEFAULT_CROSSHAIR_COLOR = (255, 255, 255)

CROSSHAIR_SURFACE_SIZE_KEY = 'crosshair_size'
CROSSHAIR_LINE_SIZE_KEY = 'crosshair_line_size'
CROSSHAIR_DOT_EXISTS_KEY = 'crosshair_dot_exists'
CROSSHAIR_DOT_SIZE_KEY = 'crosshair_dot_size'
CROSSHAIR_LINE_CENTER_DISTANCE_KEY = 'crosshair_line_center_distance'
CROSSHAIR_LINE_WIGHT_KEY = 'crosshair_line_wight'
CROSSHAIR_ROTATE_KEY = 'crosshair_rotate_angle'
CROSSHAIR_COLOR_KEY = 'crosshair_color'