from settings.screen import X_SCALE, Y_SCALE


class ButtonsConst:
    DEFAULT_BUTTON_X_SIZE = 150 * X_SCALE
    DEFAULT_BUTTON_HALF_X_SIZE = DEFAULT_BUTTON_X_SIZE // 4
    DEFAULT_BUTTON_Y_SIZE = 50 * Y_SCALE
    DEFAULT_BUTTON_HALF_Y_SIZE = DEFAULT_BUTTON_Y_SIZE // 4
    DEFAULT_CLICK_DELAY = 0.5  # seconds
    DEFAULT_BORDER_WIDTH = 1
    CLICK_ANIMATION_DURATION = 0.5

    SMALL_BUTTON_X_SIZE = 50 * X_SCALE
    SMALL_BUTTON_Y_SIZE = 50 * Y_SCALE
